### ISSUE TITLE
Monti APM Error: Reached maximum retry limit for Request failed: 502

### ISSUE THREAD

**Issue by banjerluke** [monti-apm/monti-apm-agent#29]
This shows up again and again in my server logs. Sometimes the trailing number is 520, 525, or 504, but usually its 502... Not sure how (or if) it's affecting things. Data is still showing up in Monti APM...

```
...
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 525
Monti APM Error: Reached maximum retry limit for Request failed: 525
Monti APM Error: Reached maximum retry limit for Request failed: 502
Monti APM Error: Reached maximum retry limit for Request failed: 502
...
```

**Comment by zodern** [comment]
I deployed an update today which should fix it. If you see this again, it would be helpful to get the timestamp for the log. If you are using mup, you can use the `-t` option with `mup logs`.

**Comment by banjerluke** [comment]
Still getting it. Here's the most recent episode, which affected all six of my load-balanced servers:

```
2020-07-21T09:09:19Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:09:20Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:09:21Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:09:35Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:09:35Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:09:35Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:11:46Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:11:46Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:11:47Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:12:01Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:12:02Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:12:02Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:12Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:13Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:14Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:28Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:28Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:28Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:39Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:39Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:41Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:54Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:55Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:55Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:05Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:05Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:07Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:20Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:21Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:21Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:31Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:31Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:33Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:47Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:47Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:48Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:23:43Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 523
2020-07-21T09:23:44Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 523
2020-07-21T09:23:58Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:24:13Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:24:14Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:24:14Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:25:46Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 523
2020-07-21T09:25:55Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:26:10Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:26:24Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:26:39Z server_2 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:26:39Z server_4 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:28:12Z server_5 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:28:22Z server_6 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:28:36Z server_3 | Monti APM Error: Reached maximum retry limit for Request failed: 522
```

Here's the logs from just one server if it helps:

```
2020-07-21T09:09:20Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:11:46Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:14:12Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:16:39Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:19:05Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:21:31Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:23:58Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522
2020-07-21T09:26:24Z server_1 | Monti APM Error: Reached maximum retry limit for Request failed: 522

```

It looks like no data was coming in until this string of errors; shortly thereafter, it started coming in. This was shortly after 2am on this graph (Pacific time):

![image](https://user-images.githubusercontent.com/15148/88085664-04aa4c80-cb3b-11ea-8d35-7a942142957c.png)

**Comment by banjerluke** [comment]
Also, in case it's relevant, I have these env vars set on my servers:

```
MONTI_OPTIONS_ENABLE_ERROR_TRACKING=false
MONTI_UPLOAD_SOURCE_MAPS=false
```

**Comment by zodern** [comment]
Last night there were some network issues in one of the data centers we use, which caused the engine to be down for 20 minutes.

**Comment by zodern** [comment]
The engine hasn't had any issues the past month, so I am going to close this.

**Comment by diavrank** [comment]
Hi @zodern , I got the same error in my meteor app some days ago:

```
app        | 2021-01-05T15:43:04.016221019Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:44:24.034893386Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:46:44.021432840Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:47:44.126164397Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:49:04.115968088Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:51:24.078536481Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:52:24.056537163Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:53:44.400305901Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:54:43.790886553Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:56:03.086207349Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-05T15:58:24.578320195Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-06T12:31:24.610759426Z Monti APM Error: Reached maximum retry limit for Request failed: 520
app        | 2021-01-07T08:42:46.237687887Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-07T08:43:06.361438572Z Monti APM Error: Reached maximum retry limit for Request failed: 520
app        | 2021-01-07T08:43:27.184970328Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-07T08:43:27.607940124Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-07T08:44:06.166281570Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-07T08:44:26.262666902Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-07T08:44:46.373388457Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-07T08:44:46.761647230Z Monti APM Error: Reached maximum retry limit for Request failed: 504
app        | 2021-01-07T08:45:26.154856078Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-07T08:45:46.260806580Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-07T08:46:07.187861289Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-07T08:46:07.884422419Z Monti APM Error: Reached maximum retry limit for Request failed: 504
app        | 2021-01-07T08:46:27.509672239Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-29T00:46:19.439258266Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-29T00:46:39.062790077Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-29T00:46:59.986101259Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-29T00:47:39.507069183Z Monti APM Error: Reached maximum retry limit for Request failed: 520
app        | 2021-01-29T00:47:59.153446344Z Monti APM Error: Reached maximum retry limit for Request failed: 525
app        | 2021-01-29T00:48:19.948285539Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-29T00:48:20.215769669Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-01-29T00:48:59.154847698Z Monti APM Error: Reached maximum retry limit for Request failed: 520
app        | 2021-02-02T05:21:06.885904586Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-02-02T05:21:45.617550707Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-02-02T05:21:48.322049039Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-02-03T00:42:47.664311394Z Monti APM Error: Reached maximum retry limit for Request failed: 502
app        | 2021-02-03T02:50:47.227265432Z Monti APM Error: Reached maximum retry limit for Request failed: 502
...
```
I use the **free version** of Monti APM, could it be for that?
I realized of this today, and when I wanted to login in my meteor app, it was very slow and I had issues with authentication, (it logout me out after a few seconds). I don't know if this was due to Monti APM or maybe it was receiving an attack. Some moments later (when I entered through ssh to see logs), the application returned to behaving normally. 

**Notes:**
Meteor 1.11.1
I use a docker container (disney/meteor-base)

**Comment by zodern** [comment]
Last week I improved how we monitor the API used by the agent, and fixed many causes behind requests failing. Also, if you update the to the latest version of the agent there are some performance improvements.

**Comment by diavrank** [comment]
Hi @zodern , I realized that the problem in my case maybe was caused for another package `tunguska-reactive-aggregate` v1.3.5 , so, it seems that it has a bug in its latest version that maybe provoked that errors in Monti APM (since provoke to a meteor app get freeze after invoke lookup reactive aggregate, so, this maybe provoke to disconnect it from monti apm)

**Comment by smohantyCME** [comment]
@zodern I just saw 4 of these same errors in both my sandbox and prod apps. They were both at around the same time of 13:44 UTC on 1/25/22.

@diavrank  I'm also running ReactiveAggregate, although I don't think a call to it was done at the time of the error. Do you have a link to where it says there's a bug in that package that can affect MontiAPM.

Thanks all!

**Comment by banjerluke** [comment]
I got a couple dozen of those 502 errors in the logs at the exact same time as you, over the span of about 30 seconds or so. Note that I'm running 8 servers, which may explain why I saw more of them than you. For what it's worth, I don't have any aggregation-related packages in my app.

**Comment by smohantyCME** [comment]
Just saw this again in logs today at 1235-1238 PM UTC. I also saw ` Reached maximum retry limit for connect ETIMEDOUT 104.26.4.231:443` looks like it's attempting to send through `https` to a Cloudflare service in the midwest US (guessing it's Monti)

**Comment by bensquire** [comment]
We've been seeing a lot of these recently on our free and paid account.

**Comment by a4xrbj1** [comment]
@zodern - this seems to always come up when there's some network problem on your end. This is from yesterday:
![Screenshot 2023-10-03 at 18 46 54](https://github.com/monti-apm/monti-apm-agent/assets/13525267/d86e35bf-34c9-47c2-9e2c-af3d3056775d)

86 errors over a period of 29 minutes. Is there any way how we can avoid getting our logs files plastered with this?

**Comment by cormip** [comment]
Still potentially an (occasional?) issue:
```
42mns
2024-12-21 06:53:12-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:53:22-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:53:22-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:54:38-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:54:42-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:54:42-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:54:48-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:54:48-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:54:57-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:54:57-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:54:58-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:54:58-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:55:02-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:55:02-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:55:07-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 500
w1k67
2024-12-21 06:55:17-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:55:22-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:55:22-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:55:47-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 504
42mns
2024-12-21 06:56:42-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 500
42mns
2024-12-21 06:57:32-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:37-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:37-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 504
m43ht
2024-12-21 06:57:38-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 504
m43ht
2024-12-21 06:57:38-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 504
42mns
2024-12-21 06:57:42-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:57:42-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:47-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:47-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 504
m43ht
2024-12-21 06:57:48-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:57:52-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:57-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:57-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:57:57-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:57:58-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:57:58-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:57:58-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:58:02-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:58:02-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:58:17-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:58:18-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
m43ht
2024-12-21 06:58:18-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 06:58:22-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
w1k67
2024-12-21 06:58:37-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
42mns
2024-12-21 07:00:02-05:00Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 502
```

**Comment by zodern** [comment]
@cormip thanks for sharing that. What time zone is the timestamp for the logs? We did detect 12 hours ago there were a couple minutes where 3% of the requests failed, but I'm not sure if that matches your logs. When you view the app in Monti APM, are you using app.montiapm.com, or app-us.montiapm.com?  Do you have any older logs showing `Monti APM Error:` from the past couple days?

If you prefer, you can send us the information through the "Support" form when you are logged into Monti APM - the button is in the header.
