### ISSUE TITLE
Monti APM Error: Reached maximum retry limit for Request failed: 502

### ISSUE THREAD

**Issue by a4xrbj1** [monti-apm/monti-apm-agent#67]
I'm getting this error in our log files every couple of days:

`Monti APM Error: Reached maximum retry limit for Request failed: 502`

No other info available from the log file.

**Comment by zodern** [comment]
Sometimes the api used by the agent takes too long to respond. I deployed a fix today that fixes the main cause.

**Comment by a4xrbj1** [comment]
Unfortunately the errors still comes up. Had a bunch of:

```
Monti APM Error: Reached maximum retry limit for Request failed: 502

Monti APM Error: Reached maximum retry limit for Request failed: 500

Monti APM Error: Reached maximum retry limit for Request failed: 525
```

between 13:31 and 13:33 (just two hours ago) today. 70 Errors within the last 7 days.

**Comment by zodern** [comment]
On Monday I made a few more improvements, and our monitoring hasn't detected any problems with the api since then.
